version: '3.9'

services:
  db:
    container_name: Lunch-Postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Lunch123
    volumes:
      - lunch-data:/var/lib/postgresql/data

  emp-lunch-backend:
    container_name: lunch-backend
    ports:
      - 5000:5000
    environment:
      ConnectionStrings__PostgresConnection: "Server=db;Port=5432;Database=Lunch-Database;User Id=postgres;Password=Lunch123;URL: 1"
    build:
      context: backend
    depends_on:
      - db

  lunch-frontend:
    container_name: lunch-frontend
    build:
      context: frontend
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80

volumes:
  lunch-data: