version: '3.9'

services:
  db:
    container_name: Lunch-Postgres
    image: postgres:12.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Lunch123
    volumes:
      - lunch-data:/var/lib/postgresql/data

  emp-lunch-backend:
    container_name: lunch-backend
    ports:
      - 8080:8080
    environment:
      VITE_HOST_URL: 1
    build:
      context: HaveLunch
    depends_on:
      - db



volumes:
  lunch-data: