name: team3-have-lunch

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-run-test:
    runs-on: "ubuntu-latest"
    name: "CI frontend"
    defaults:
      run:
        working-directory: './frontend'

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: build
        run: |
          npm ci
          npm run build-uat
    
    
  

