name: team3-have-lunch

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-run-test:
    runs-on: "ubuntu-latest"
    name: "CI frontend"
    defaults:
      run:
        working-directory: './frontend'

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: build
        run: |
          npm ci
          npm run build-uat
  

  run-bdd:
    runs-on: "ubuntu-latest"
    name: "Frontend Build"
    needs: push-to-uat
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"

      - name: "Install Dependencies"
        run: |
          cd frontend
          npm ci
        env:
          VITE_HOST_URL: ${{ secrets.VITE_HOST_URL }}
          VITE_HOST_PORT: ${{ secrets.VITE_HOST_PORT }}
          PROD: "true"

      - name: "Setup Chrome"
        uses: browser-actions/setup-chrome@v1

      - name: "Run Tests"
        run: |
          cd frontend
          npm test
        env:
          VITE_HOST_URL: ${{ secrets.VITE_HOST_URL }}
          VITE_HOST_PORT: ${{ secrets.VITE_HOST_PORT }}
          PROD: "true"

