name: team3-have-lunch

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-run-test:
    runs-on: "ubuntu-latest"
    name: "CI backend"
    defaults:
      run:
        working-directory: './backend/'

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: cleanup
        run: dotnet clean HaveLunch.sln

      - name: restore dependencies
        run: dotnet restore HaveLunch.sln

      - name: build
        run: dotnet test HaveLunch.Tests/HaveLunch.Tests.csproj

      - name: build artifact
        run: dotnet publish HaveLunch/HaveLunch.csproj -c Release -o ./publish


  run-bdd:
    runs-on: "ubuntu-latest"
    name: "Frontend Build"
    needs: build-and-run-test
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"

      - name: "Install Dependencies"
        run: |
          cd frontend
          npm ci
        env:
          VITE_HOST_URL: ${{ secrets.VITE_HOST_URL }}
          VITE_HOST_PORT: ${{ secrets.VITE_HOST_PORT }}
          PROD: "true"

      - name: "Setup Chrome"
        uses: browser-actions/setup-chrome@v1

      - name: "Run server"
        run: |
          cd frontend
          npm run dev
      - name: "Run Tests"
        run: |
          cd frontend
          npm test
        env:
          VITE_HOST_URL: ${{ secrets.VITE_HOST_URL }}
          VITE_HOST_PORT: ${{ secrets.VITE_HOST_PORT }}
          PROD: "true"